language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t tkdgus115/test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true tkdgus115/test npm test

after_success:
  - docker build -t tkdgus115/docker-frontend ./frontend
  - docker build -t tkdgus115/docker-backend ./backend
  - docker build -t tkdgus115/docker-nginx ./nginx
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

- docker push tkdgus115/docker-frontend
- docker push tkdgus115/docker-backend
- docker push tkdgus115/docker-nginx